# Generated by Django 2.1.7 on 2019-03-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localuser',
            name='premium',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
